version : "3.8"
services:
    rp:
      container_name: rp-server
      image: rp-opensource:latest
      build:
        context: .
        dockerfile: ./rpserver/Dockerfile
      ports:
        - "8080:8080"
      restart: always
    fido2:
      container_name: fido2-demo
      image: fido2-opensource:latest
      build:
        context: .
        dockerfile: ./fido2-demo/demo/Dockerfile
      ports:
        - "8081:8081"
      restart: always
